// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: PersonalInfo.proto

#include "PersonalInfo.pb.h"
#include "PersonalInfo.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* PersonalInformationService_method_names[] = {
  "/PersonalInformationService/SetInfo",
};

std::unique_ptr< PersonalInformationService::Stub> PersonalInformationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PersonalInformationService::Stub> stub(new PersonalInformationService::Stub(channel, options));
  return stub;
}

PersonalInformationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetInfo_(PersonalInformationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PersonalInformationService::Stub::SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::PersonalInfoReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::PersonalInfoRequest, ::PersonalInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetInfo_, context, request, response);
}

void PersonalInformationService::Stub::async::SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::PersonalInfoRequest, ::PersonalInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetInfo_, context, request, response, std::move(f));
}

void PersonalInformationService::Stub::async::SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>* PersonalInformationService::Stub::PrepareAsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::PersonalInfoReply, ::PersonalInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>* PersonalInformationService::Stub::AsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

PersonalInformationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PersonalInformationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PersonalInformationService::Service, ::PersonalInfoRequest, ::PersonalInfoReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PersonalInformationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::PersonalInfoRequest* req,
             ::PersonalInfoReply* resp) {
               return service->SetInfo(ctx, req, resp);
             }, this)));
}

PersonalInformationService::Service::~Service() {
}

::grpc::Status PersonalInformationService::Service::SetInfo(::grpc::ServerContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


