// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: PersonalInfo.proto
#ifndef GRPC_PersonalInfo_2eproto__INCLUDED
#define GRPC_PersonalInfo_2eproto__INCLUDED

#include "PersonalInfo.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class PersonalInformationService final {
 public:
  static constexpr char const* service_full_name() {
    return "PersonalInformationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::PersonalInfoReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>> AsyncSetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>>(AsyncSetInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>> PrepareAsyncSetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>>(PrepareAsyncSetInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>* AsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PersonalInfoReply>* PrepareAsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::PersonalInfoReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>> AsyncSetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>>(AsyncSetInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>> PrepareAsyncSetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>>(PrepareAsyncSetInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, std::function<void(::grpc::Status)>) override;
      void SetInfo(::grpc::ClientContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>* AsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PersonalInfoReply>* PrepareAsyncSetInfoRaw(::grpc::ClientContext* context, const ::PersonalInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetInfo(::grpc::ServerContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetInfo(::grpc::ServerContext* context, ::PersonalInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::PersonalInfoReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::PersonalInfoRequest, ::PersonalInfoReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::PersonalInfoRequest* request, ::PersonalInfoReply* response) { return this->SetInfo(context, request, response); }));}
    void SetMessageAllocatorFor_SetInfo(
        ::grpc::MessageAllocator< ::PersonalInfoRequest, ::PersonalInfoReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::PersonalInfoRequest, ::PersonalInfoReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PersonalInfoRequest, ::PersonalInfoReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::PersonalInfoRequest, ::PersonalInfoReply>* streamer) {
                       return this->StreamedSetInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetInfo(::grpc::ServerContext* /*context*/, const ::PersonalInfoRequest* /*request*/, ::PersonalInfoReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PersonalInfoRequest,::PersonalInfoReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetInfo<Service > StreamedService;
};


#endif  // GRPC_PersonalInfo_2eproto__INCLUDED
